# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20170207_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
