# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
