# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
