# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170227_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='optin',
            field=models.BooleanField(default=True),
        ),
    ]
