# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20170227_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
