# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_group_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=17),
        ),
    ]
