# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='twilio_sid',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
