# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0006_auto_20170214_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='statuss',
        ),
        migrations.RemoveField(
            model_name='message',
            name='statuss',
        ),
    ]
