# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0007_auto_20170214_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
