# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesapp', '0008_auto_20170214_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='statuses',
            field=models.CharField(choices=[('Q', 'queued'), ('F', 'failed'), ('S', 'sent'), ('D', 'delivered'), ('U', 'undelivered')], default='Q', max_length=1),
        ),
        migrations.AddField(
            model_name='message',
            name='statuses',
            field=models.CharField(choices=[('Q', 'queued'), ('F', 'failed'), ('S', 'sent'), ('D', 'delivered'), ('U', 'undelivered')], default='Q', max_length=1),
        ),
    ]
